
title: Business Innovation
description: Premium Business Solutions
baseurl: ""
url: ""

collections:
  tools:
    output: false
  projects:
    output: true
  materials:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "materials"
    values:
      layout: "material"
